### PR TITLE
File Store Bot

### PR DESCRIPTION
**Pull request by Raj-Anonymous**
File Store Bot

### CODE REVIEW

**Comment by Raj-Anonymous** [comment]
What Is This...? I Don't Know English..😭😭

**Comment by unknown-01-hacker** [comment]
```🙄nothing yet ```

**Comment by Raj-Anonymous** [comment]
OK... Why Your Name Is Unknown..? You Don't Name ah ? 😂🤣

**Comment by unknown-01-hacker** [comment]
>My name is **Pruthviraj**  😂 🤣

>            You find me in telegram  @Danger_Kannada_Admin
>                   my Group is  @pruthvi_RJ_Group
             
               "If you're Bad 🤨 I'm the worst 😎"
                        🙄🙄🙄

**Comment by Raj-Anonymous** [comment]
Ohhh.k

**Comment by unknown-01-hacker** [comment]
😋 i m your friend  telegram named has ``offline`` 😳

**Comment by Raj-Anonymous** [comment]
I know , You Are Jishnu..😀😀

**Pull request closed without merging**
